### ISSUE TITLE
Update-APReleaseEnvironment broken for on-prem installs

### ISSUE THREAD

**Issue by scrthq** [Dejulia489/AzurePipelinesPS#1]
**Client**: PowerShell 5.1 on Win10 1809
**Server**: Azure DevOps Server 2019 RC1 (on-prem)
**API Versions**: `4.1-preview.5`, `5.1-preview.6`

Issue is caused due to Azure DevOps Services (hosted) prepending the URL with `vsrm`. On-prem installs don't have the same subdomain prepended, it's still just the standard URL scheme for this endpoint in on-prem installs: 

`$Instance/$Collection/$Project/_apis/Release/releases/$ReleaseId/environments/$($EnvironmentId)?api-version=$APIVersion`

Screenshot of the error:

![image](https://user-images.githubusercontent.com/12724445/50673735-d0495c80-0fa5-11e9-9f24-89167f3fa230.png)

PR coming up with the fix asap, already validated it by using the REST API directly 😄

**Comment by scrthq** [comment]
[PR #2](https://github.com/Dejulia489/AzurePipelinesPS/pull/2) submitted!

**Comment by Dejulia489** [comment]
Great catch, I haven't worked with the 2019.1 update yet. Can you please include the following
`'*.visualstudio.com` in your instance validation. Some projects in Azure DevOps support both urls. 

Let me know if you have any questions or concerns. 

Thanks, 
Michael

**Comment by scrthq** [comment]
Makes sense! Adding it shortly!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by scrthq** [comment]
Added and validated:

1. Legacy `visualstudio.com` still prepending:

![image](https://user-images.githubusercontent.com/12724445/50721257-1b38a200-1082-11e9-879d-2cc339e8ab43.png)

2. New `dev.azure.com` still prepending:

![image](https://user-images.githubusercontent.com/12724445/50721259-268bcd80-1082-11e9-81b0-9e93f32b45da.png)

3. On-prem Azure DevOps Server 2019 still _**not**_ prepending:

![image](https://user-images.githubusercontent.com/12724445/50721265-4a4f1380-1082-11e9-8f8e-4008c6233bc5.png)


Push coming momentarily!
