### ISSUE TITLE
Install-APAgent /distributedTask/packages/agent endpoint moved?

### ISSUE THREAD

**Issue by frackham** [Dejulia489/AzurePipelinesPS#12]
Am currently trying to use Install-APAgent to install an agent and add to an existing pool, but get: 
```
Install-APAgent : [Install-APAgent]: Unable to locate package url!
```

When I use the same parameters for other REST api calls, they work.

Trying to call (have obviously changed pat, collection, project from real data :) ):
```
$splat = @{
    Collection          = 'XXX'
    Project             = 'YYY'
    Instance            = 'https://dev.azure.com/'
    PersonalAccessToken = 'ecqxsvhakbhsezdy7t6zm3okvraasdasdura5dnwrkyn2lklt4u3a'
    ApiVersion          = 'vNext'
    SessionName         = 'mySession'
}

#https://dev.azure.com/xxx/yyy/_apis/distributedTask/packages/agent
$session = New-APSession @splat

Install-APAgent -PatAuthentication -apiversion $session.ApiVersion -PersonalAccessToken $session.PersonalAccessToken -DeploymentGroupName 'Dev' -DeploymentGroupTag 'myTag' -Collection $session.Collection -Project $session.Project -Platform 'Windows' -Instance $session.Instance -Verbose
```

When I try the same in postman, using a working collection using the same PAT (ie how I currently get release / build lists) I hit a redirect:
![image](https://user-images.githubusercontent.com/2105204/68585371-fa976080-0479-11ea-8f34-bf9d04ebbcd6.png)

**Comment by Dejulia489** [comment]
Try setting the ApiVersion = '5.0-preview'

**Comment by Dejulia489** [comment]
Is this still an issue? I have added session support to Install-APAgent.

**Comment by Dejulia489** [comment]
This has been resolved
