### ISSUE TITLE
Release definition list property expanding does not work

### ISSUE THREAD

**Issue by kuulemart** [Dejulia489/AzurePipelinesPS#13]
When executing `Get-APReleaseDefinitionList` with -Expand <property> parameter, query string `Expand=<property>` is added, but according to doc the query key should have $ prefix. As a result, expected property is not in result.

Command: 
`Get-APReleaseDefinitionList -Session test -SearchText <search text> -Expand environments -Verbose`

full query from verbose:

`GET https://vsrm.dev.azure.com/<org>/<proj>/_apis/release/definitions?SearchText=<search text>&Expand=environments&api-version=5.0`

but it should be:

`GET https://vsrm.dev.azure.com/<org>/<proj>/_apis/release/definitions?SearchText=<search text>&$expand=environments&api-version=5.0`

Doc: https://docs.microsoft.com/en-us/rest/api/azure/devops/release/definitions/list?view=azure-devops-rest-5.0

**Comment by kuulemart** [comment]
Created pull request for a fix: https://github.com/Dejulia489/AzurePipelinesPS/pull/14

**Comment by Dejulia489** [comment]
Resolved with the latest version:
https://www.powershellgallery.com/packages/AzurePipelinesPS/2.0.53
