### ISSUE TITLE
Would you be interested in a pull/feature request which would integrate Azure Key Vault support in Variable Groups?

### ISSUE THREAD

**Issue by rbleattler** [Dejulia489/AzurePipelinesPS#19]
Would you be interested in a pull/feature request which would integrate Azure Key Vault support in the Variable Groups functions?

**Comment by Dejulia489** [comment]
No doubt, send it over so I can take a look.

**Comment by rbleattler** [comment]
> No doubt, send it over so I can take a look.

I'm actively working. I'll send it as soon as I have a working version. Thanks!

**Comment by Dejulia489** [comment]
Closed for inactivity. Will reopen if needed.
