### ISSUE TITLE
Update-APBuildDefinition DefinitionExistsException error

### ISSUE THREAD

**Issue by Celakanth-VSI** [Dejulia489/AzurePipelinesPS#20]
Hay there not sure what the issue could be but when I run the Update-APBuidDefinition I get the following
Invoke-RestMethod : {"$id":"1","innerException":null,"message":"Build pipeline PIPELINE_NAME already exists for project 
PROJECT_NAME","typeName":"Microsoft.TeamFoundation.Build.WebApi.DefinitionExistsException, 
Microsoft.TeamFoundation.Build2.WebApi","typeKey":"DefinitionExistsException","errorCode":0,"eventId":3000}
At C:\Program Files\WindowsPowerShell\Modules\AzurePipelinesPS\3.1.39\AzurePipelinesPS.psm1:28597 char:20
+         $results = Invoke-RestMethod @authenticatedRestMethodSplat
+                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-RestMethod], WebException
    + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

IF I change the name of the pipeline it creates a new one with all the past builds from the original one

Any reason or anything I might be missing

**Comment by Dejulia489** [comment]
Update the definition to a new name and set the id of the definition to 0.

**Comment by Dejulia489** [comment]
Closing this issue, if you are still having issue please feel free to reopen.
