### ISSUE TITLE
Save-APSession fails due to missing AzurePipelinesPS folder in $env:APPDATA

### ISSUE THREAD

**Issue by scrthq** [Dejulia489/AzurePipelinesPS#3]
Folder needs to be created if it does not already exist, otherwise the default path when calling `Save-APSession` fails due to a part of the path being missing:

![image](https://user-images.githubusercontent.com/12724445/50677031-3392b900-0fbd-11e9-89b2-a612a2a46591.png)

Fix coming up in the same [PR #2](https://github.com/Dejulia489/AzurePipelinesPS/pull/2)

**Comment by Dejulia489** [comment]
Thanks for contributing, you have been added to the contributors section!

**Comment by scrthq** [comment]
My pleasure! Thanks for the great framework, pretty easy to extend, should have some more additions coming in the future! Happy to help bug squash as well 💪

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
