### ISSUE TITLE
PARAMETER PropertyFilters seems to be not working

### ISSUE THREAD

**Issue by Paladin33rus** [Dejulia489/AzurePipelinesPS#30]
Hello @Dejulia489 !

Could you pls shed some light on `Get-APReleaseDefinition.ps1` usage?

I've trying to retrive approvers data, like you suggested [here](https://stackoverflow.com/a/57085370) but getting almost same result as running cmdlet without `-PropertyFilters` key. The only difference is given on pic below
![image](https://user-images.githubusercontent.com/125548803/219324213-1649aefd-6de7-4ed4-bf86-8a4fcedcc974.png)
LHS: `Get-APReleaseDefinition -Session 'Session' -DefinitionId 2`
RHS: `Get-APReleaseDefinition -Session 'Session' -DefinitionId 2 -PropertyFilters 'environments,_links'`

Header for GET request is containing valid payload.

**Comment by Dejulia489** [comment]
Update your session api version to 5.1-preview and try again.

**Comment by Paladin33rus** [comment]
So, my problem was:
I was trying to provide **bare json file** to the tool input, while it **expecting PS Object**. `ConvertFrom-Json` comandlet is fixed problem. Managed to alter Release Definitions in bulk.

Tested on:

> WIN10x64
> PS 7.3.3
> AzurePipelinesPS 4.0.32
> API 5.1-preview
