### ISSUE TITLE
APPDATA is not defined on MacOS

### ISSUE THREAD

**Issue by createk-design** [Dejulia489/AzurePipelinesPS#4]
Hi - in the Get-APSession method there is a reference to APPDATA. On MacOS this is not defined and Test-Path then fails. I could make this work by adding the following to my environment:
export APPDATA="/Users/myname/"
Perhaps you could test for this environment variable and if it doesn't exist then test for a HOME path? 

Otherwise thank you so much - this is an awesome piece of work that has made my life so much easier.

**Comment by Dejulia489** [comment]
I will look into this and get back to you.

Sorry for the delay and thank you!

**Comment by Dejulia489** [comment]
This has been resolved in the new version of [AzurePipelinesPS - 2.0.33](https://www.powershellgallery.com/packages/AzurePipelinesPS), sorry for the delay!

Tell all your Mac friends they can now use AzurePipelinesPS.
